version: "3"
services:
  web_proxy:
    container_name: webserverproxy
    image: nginx:latest
    ports:
        - "8080:80"
    depends_on:
      - web1
      - web2
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  
  web1:
    container_name: webserver1
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html:ro

  web2:
    container_name: webserver2
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www/html:ro

