global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus_main:9090

  - job_name: nodes
    scrape_interval: 5s
    static_configs:
    - targets:
      - 172.31.40.230:9100
      - 172.31.33.171:9100
      - 172.31.32.195:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 172.31.40.230:8081
      - 172.31.33.171:8081
      - 172.31.32.195:8081
